"""Versioned schema contracts shared by Phase 3 projectors and writers."""

from finances_simulator.contracts.ground_truth_v2 import (
    BalanceSheetGroundTruthV2,
    CardTransactionGroundTruthV2,
    CustomerGroundTruthV2,
    CustomerMonthGroundTruthV2,
    GroundTruthModelV2,
    InvestmentTransactionGroundTruthV2,
    LoanPaymentGroundTruthV2,
    TransactionGroundTruthV2,
)
from finances_simulator.contracts.observed_v2 import (
    AccountV2,
    BalanceV2,
    CardInvoiceItemV2,
    CardInvoiceV2,
    CardTransactionV2,
    CreditCardV2,
    CreditLimitV2,
    InvestmentBalanceV2,
    InvestmentTransactionV2,
    InvestmentV2,
    LoanBalanceV2,
    LoanPaymentV2,
    LoanV2,
    ObservationModelV2,
    TransactionV2,
)

__all__ = [
    "AccountV2",
    "BalanceSheetGroundTruthV2",
    "BalanceV2",
    "CardInvoiceItemV2",
    "CardInvoiceV2",
    "CardTransactionGroundTruthV2",
    "CardTransactionV2",
    "CreditCardV2",
    "CreditLimitV2",
    "CustomerGroundTruthV2",
    "CustomerMonthGroundTruthV2",
    "GroundTruthModelV2",
    "InvestmentBalanceV2",
    "InvestmentTransactionGroundTruthV2",
    "InvestmentTransactionV2",
    "InvestmentV2",
    "LoanBalanceV2",
    "LoanPaymentGroundTruthV2",
    "LoanPaymentV2",
    "LoanV2",
    "ObservationModelV2",
    "TransactionGroundTruthV2",
    "TransactionV2",
]
