"""One-page Streamlit demo: generate a synthetic client, estimate their income, show the evidence.

Rendering only. Every simulator and estimator call lives in :mod:`demo_app.service`, which also
fixes the order the two sides may run in. Nothing on this page reads the private truth except the
places that say, on the page, that they are doing so.
"""

from __future__ import annotations

import sys
from pathlib import Path

import altair as alt
import pandas as pd
import streamlit as st

# Streamlit puts the script's own directory on the path, not the repository root, so the package
# this module belongs to is not importable by default. Added before the first `demo_app` import so
# `streamlit run demo_app/app.py` works from anywhere.
if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from demo_app.export import TRUTH_DISCLAIMER, evidence_filename, evidence_json
from demo_app.formatting import (
    COMPONENT_LABELS,
    CONFIDENCE_COMPONENTS,
    LIFE_EVENT_LABELS,
    QUANTILE_UNAVAILABLE_REASONS,
    ROUTING_REASONS,
    basis_points,
    describe,
    money,
    money_major,
    money_md,
    percent,
    signed_percent,
)
from demo_app.profiles import PROFILES, supported_months
from demo_app.service import (
    DemoConfigurationError,
    DemoResult,
    load_estimator,
    run_demo,
)

TRUTH_LABEL = "Evaluation only - never provided to the estimator"

TRUTH_SERIES = "Actual income (truth)"
SERIES_COLORS = {
    TRUTH_SERIES: "#9ca3af",
    "Estimated realized": "#2563eb",
    "Estimated sustainable": "#d97706",
}
# Drawn thick so a coinciding estimate sits visibly inside it rather than hiding it.
SERIES_WIDTHS = {TRUTH_SERIES: 7.0, "Estimated realized": 2.0, "Estimated sustainable": 2.0}

st.set_page_config(
    page_title="Open Finance Income Estimator",
    page_icon="📊",
    layout="wide",
)


@st.cache_resource(show_spinner=False)
def cached_estimator():
    """Load the promoted artifact pair once per server process."""

    return load_estimator()


# ---------------------------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------------------------

st.title("Open Finance Income Estimator")
st.caption(
    "Explainable income estimation from consented financial data. "
    "This page runs the simulator and the estimator together, in one process."
)
st.warning(
    "**Synthetic data only.** Every client, account, and transaction on this page is generated by "
    "the simulator. No real client data, credential, or provider response is involved.",
    icon="⚠️",
)

try:
    estimator = cached_estimator()
except DemoConfigurationError as error:
    st.error(f"The demo cannot start: {error}", icon="🚫")
    st.stop()

# ---------------------------------------------------------------------------------------------
# 1. Controls
# ---------------------------------------------------------------------------------------------

with st.container(border=True):
    st.subheader("1. Choose a client")
    controls = st.columns([3, 1, 1, 1])

    profile = controls[0].selectbox(
        "Client profile",
        options=PROFILES,
        format_func=lambda item: item.label,
        key="profile",
    )
    months_options = supported_months(profile.key)
    months = controls[1].radio(
        "History length",
        options=months_options,
        format_func=lambda value: f"{value} months",
        key=f"months_{profile.key}",
        help=(
            "Longer histories are offered only where the scenario configures income sources that "
            "far. Beyond that point every source ends mid-window and the comparison stops meaning "
            "anything."
        ),
    )
    seed = controls[2].number_input(
        "Seed",
        min_value=0,
        max_value=999_999,
        value=profile.default_seed,
        step=1,
        key=f"seed_{profile.key}",
        help="The same profile, seed, and history length always produce identical numbers.",
    )
    controls[3].markdown("<div style='height:1.8rem'></div>", unsafe_allow_html=True)
    generate = controls[3].button("Generate financial history", type="primary")

    st.markdown(f"**{profile.label}.** {profile.description}")
    st.markdown(f"*Demonstrates:* {profile.demonstrates}")
    if len(months_options) == 1:
        st.caption(
            f"This scenario configures {months_options[0]} months of income, so that is the only "
            "history length offered."
        )

if generate:
    try:
        with st.spinner("Simulating the client and running the estimator..."):
            st.session_state["result"] = run_demo(profile.key, seed=int(seed), months=int(months))
    except DemoConfigurationError as error:
        st.error(str(error), icon="🚫")
    except Exception as error:  # noqa: BLE001 - the page must survive any generation failure
        st.exception(error)

result: DemoResult | None = st.session_state.get("result")
if result is None:
    st.info(
        "Pick a profile and press **Generate financial history** to run the full flow: the "
        "simulator builds a complete hidden financial life, the estimator sees only the consented "
        "part of it, and the two are compared afterwards.",
        icon="👆",
    )
    st.stop()

if result.profile.key != profile.key or result.seed != int(seed) or result.months != int(months):
    st.info(
        f"Showing the last run: **{result.profile.label}**, seed {result.seed}, "
        f"{result.months} months. Press **Generate financial history** to run the new selection.",
        icon="ℹ️",
    )

if result.profile.caveat:
    st.error(result.profile.caveat, icon="⚠️")

# ---------------------------------------------------------------------------------------------
# 2. Executive result
# ---------------------------------------------------------------------------------------------

latest = result.latest
st.subheader(f"2. Result for {latest.month}")

estimate_columns = st.columns(4)
estimate_columns[0].metric(
    "Estimated realized income",
    money_md(latest.realized_estimate_minor, result.currency),
    help="What the estimator concludes actually landed in the client's accounts that month.",
)
estimate_columns[1].metric(
    "Estimated sustainable income",
    money_md(latest.sustainable_p50_minor, result.currency),
    help="The level the estimator judges the client can rely on, not just what arrived once.",
)
if latest.has_interval:
    estimate_columns[2].metric(
        "P10 - P90 range",
        f"{money_md(latest.sustainable_p10_minor, result.currency)}"
        f" to {money_md(latest.sustainable_p90_minor, result.currency)}",
        help="An 80% interval on sustainable income, from the promoted conformal calibration.",
    )
else:
    estimate_columns[2].metric("P10 - P90 range", "abstained")
estimate_columns[3].metric(
    "Confidence",
    basis_points(latest.confidence_score_basis_points),
    help="A weighted score over coverage, history length, stability, and component agreement.",
)

if not latest.has_interval:
    st.warning(
        "**No interval published for this month.** "
        + describe(latest.quantile_unavailable_reason or "", QUANTILE_UNAVAILABLE_REASONS),
        icon="🚧",
    )

with st.container(border=True):
    st.markdown(f"##### Simulator truth &nbsp; `{TRUTH_LABEL}`")
    truth_columns = st.columns(4)
    truth_columns[0].metric(
        "Actual realized income",
        money_md(latest.truth_realized_minor, result.currency),
    )
    truth_columns[1].metric(
        "Actual sustainable income",
        money_md(latest.truth_sustainable_minor, result.currency),
    )
    truth_columns[2].metric(
        "Realized error",
        money_md(latest.realized_error_minor, result.currency),
        delta=signed_percent(latest.realized_error_percent),
        delta_color="off",
    )
    truth_columns[3].metric(
        "Sustainable error",
        money_md(latest.sustainable_error_minor, result.currency),
        delta=signed_percent(latest.sustainable_error_percent),
        delta_color="off",
    )

covered, published = result.interval_coverage
window_columns = st.columns(4)
window_columns[0].metric(
    "Realized income, mean error over the window",
    percent(result.realized_mean_absolute_percent_error),
)
window_columns[1].metric(
    "Sustainable income, mean error over the window",
    percent(result.sustainable_mean_absolute_percent_error),
)
window_columns[2].metric(
    "Interval held the truth",
    f"{covered} of {published} months" if published else "no months published",
    help="Nominal coverage is 80%. Anything far below it means the band is too narrow.",
)
window_columns[3].metric(
    "Run time",
    f"{result.total_seconds:.2f} s",
    help=(
        f"Simulation {result.generation_seconds:.2f} s, "
        f"inference {result.inference_seconds:.2f} s."
    ),
)

# ---------------------------------------------------------------------------------------------
# 3. Charts
# ---------------------------------------------------------------------------------------------


def month_to_timestamp(month: str) -> pd.Timestamp:
    return pd.Timestamp(f"{month}-01")


def build_income_frame(demo: DemoResult) -> pd.DataFrame:
    records = []
    for row in demo.month_rows:
        stamp = month_to_timestamp(row.month)
        records.append(
            {
                "month": stamp,
                "series": TRUTH_SERIES,
                "value": money_major(row.truth_realized_minor),
            }
        )
        records.append(
            {
                "month": stamp,
                "series": "Estimated realized",
                "value": money_major(row.realized_estimate_minor),
            }
        )
        records.append(
            {
                "month": stamp,
                "series": "Estimated sustainable",
                "value": money_major(row.sustainable_p50_minor),
            }
        )
    return pd.DataFrame.from_records(records).dropna(subset=["value"])


def build_band_frame(demo: DemoResult) -> pd.DataFrame:
    return pd.DataFrame.from_records(
        [
            {
                "month": month_to_timestamp(row.month),
                "p10": money_major(row.sustainable_p10_minor),
                "p90": money_major(row.sustainable_p90_minor),
            }
            for row in demo.month_rows
            if row.has_interval
        ]
    )


def build_abstention_frame(demo: DemoResult) -> pd.DataFrame:
    return pd.DataFrame.from_records(
        [
            {"month": month_to_timestamp(row.month), "reason": row.quantile_unavailable_reason}
            for row in demo.month_rows
            if not row.has_interval
        ]
    )


MONTH_AXIS = alt.Axis(format="%b %Y", tickCount={"interval": "month", "step": 1}, labelAngle=-45)

st.subheader("3. Financial history")

income_frame = build_income_frame(result)
band_frame = build_band_frame(result)
abstention_frame = build_abstention_frame(result)

layers = []
if not band_frame.empty:
    layers.append(
        alt.Chart(band_frame)
        .mark_area(opacity=0.18, color="#d97706")
        .encode(
            x=alt.X("month:T", title=None, axis=MONTH_AXIS),
            y=alt.Y("p10:Q", title=f"Monthly income ({result.currency})"),
            y2="p90:Q",
            tooltip=[
                alt.Tooltip("month:T", title="Month", format="%Y-%m"),
                alt.Tooltip("p10:Q", title="P10", format=",.2f"),
                alt.Tooltip("p90:Q", title="P90", format=",.2f"),
            ],
        )
    )
if not abstention_frame.empty:
    layers.append(
        alt.Chart(abstention_frame)
        .mark_rule(color="#dc2626", strokeDash=[2, 3], opacity=0.45, strokeWidth=5)
        .encode(
            x=alt.X("month:T", axis=MONTH_AXIS),
            tooltip=[
                alt.Tooltip("month:T", title="Month", format="%Y-%m"),
                alt.Tooltip("reason:N", title="No interval published"),
            ],
        )
    )
layers.append(
    alt.Chart(income_frame)
    .mark_line(point=False)
    .encode(
        x=alt.X("month:T", title=None, axis=MONTH_AXIS),
        y=alt.Y("value:Q", title=f"Monthly income ({result.currency})"),
        color=alt.Color(
            "series:N",
            title=None,
            scale=alt.Scale(
                domain=list(SERIES_COLORS),
                range=list(SERIES_COLORS.values()),
            ),
            legend=alt.Legend(orient="top"),
        ),
        strokeWidth=alt.StrokeWidth(
            "series:N",
            scale=alt.Scale(domain=list(SERIES_WIDTHS), range=list(SERIES_WIDTHS.values())),
            legend=None,
        ),
        opacity=alt.Opacity(
            "series:N",
            scale=alt.Scale(domain=list(SERIES_WIDTHS), range=[0.45, 1.0, 1.0]),
            legend=None,
        ),
        tooltip=[
            alt.Tooltip("month:T", title="Month", format="%Y-%m"),
            alt.Tooltip("series:N", title="Series"),
            alt.Tooltip("value:Q", title="Amount", format=",.2f"),
        ],
    )
)

if result.life_events:
    event_frame = pd.DataFrame.from_records(
        [
            {
                "date": pd.Timestamp(event.effective_date),
                "event": describe(event.event_type, LIFE_EVENT_LABELS),
            }
            for event in result.life_events
        ]
    )
    layers.append(
        alt.Chart(event_frame)
        .mark_rule(color="#a855f7", strokeDash=[4, 3], opacity=0.9, strokeWidth=2)
        .encode(
            x=alt.X("date:T", axis=MONTH_AXIS),
            tooltip=[
                alt.Tooltip("date:T", title="Date", format="%Y-%m-%d"),
                alt.Tooltip("event:N", title="Life event (truth)"),
            ],
        )
    )

st.altair_chart(alt.layer(*layers).resolve_scale(y="shared").properties(height=340))

legend_notes = [
    "The thick pale line is the simulator's actual income; where an estimate matches it "
    f"exactly, the estimate line sits inside it. `{TRUTH_LABEL}`",
    "The shaded band is the published P10-P90 interval on sustainable income.",
]
if not abstention_frame.empty:
    legend_notes.append(
        "Thick red marks are months where the estimator **declined to publish an interval** "
        "because the month fell outside its calibrated support."
    )
if result.life_events:
    legend_notes.append(
        f"Dashed purple lines are life events from the simulator. `{TRUTH_LABEL}`"
    )
st.caption("  \n".join(f"- {note}" for note in legend_notes))

if result.balance_rows:
    with st.expander("Observed balance sheet", expanded=False):
        st.caption(
            "Assembled from the consented feed only, not from simulator truth. Under partial "
            "consent these lines are incomplete on purpose: they show what the client actually "
            "exposed."
        )
        balance_frame = pd.DataFrame.from_records(
            [
                {
                    "month": month_to_timestamp(row.month),
                    "Account balance": money_major(row.account_balance_minor),
                    "Investment balance": money_major(row.investment_balance_minor),
                    "Outstanding debt": money_major(row.debt_minor),
                    "Net position": money_major(row.net_position_minor),
                }
                for row in result.balance_rows
            ]
        ).melt(id_vars="month", var_name="series", value_name="value")
        st.altair_chart(
            alt.Chart(balance_frame)
            .mark_line(point=False, strokeWidth=2)
            .encode(
                x=alt.X("month:T", title=None, axis=MONTH_AXIS),
                y=alt.Y("value:Q", title=f"Balance ({result.currency})"),
                color=alt.Color(
                    "series:N", title=None, legend=alt.Legend(orient="top", labelLimit=0)
                ),
                tooltip=[
                    alt.Tooltip("month:T", title="Month", format="%Y-%m"),
                    alt.Tooltip("series:N", title="Series"),
                    alt.Tooltip("value:Q", title="Amount", format=",.2f"),
                ],
            )
            .properties(height=260)
        )

# ---------------------------------------------------------------------------------------------
# 4. Evidence tabs
# ---------------------------------------------------------------------------------------------

st.subheader("4. Evidence")
history_tab, explanation_tab, quality_tab, how_tab = st.tabs(
    ["Financial history", "Estimator explanation", "Data quality", "How it works"]
)

with history_tab:
    st.markdown("##### Month by month")
    st.dataframe(
        pd.DataFrame.from_records(
            [
                {
                    "Month": row.month,
                    "Actual income (truth)": money(row.truth_realized_minor, result.currency),
                    "Estimated realized": money(row.realized_estimate_minor, result.currency),
                    "Realized error": signed_percent(row.realized_error_percent),
                    "Actual sustainable (truth)": money(
                        row.truth_sustainable_minor, result.currency
                    ),
                    "Estimated sustainable": money(row.sustainable_p50_minor, result.currency),
                    "P10": money(row.sustainable_p10_minor, result.currency),
                    "P90": money(row.sustainable_p90_minor, result.currency),
                    "Interval held": (
                        "-"
                        if row.interval_contains_truth is None
                        else ("yes" if row.interval_contains_truth else "no")
                    ),
                    "Confidence": basis_points(row.confidence_score_basis_points),
                    "Credits used": row.included_transaction_count,
                    "Credits excluded": row.excluded_transaction_count,
                }
                for row in result.month_rows
            ]
        ),
        width="stretch",
        hide_index=True,
    )
    st.caption(f"Columns marked *(truth)* are `{TRUTH_LABEL}`.")

    st.markdown("##### What the estimator received")
    counts = {
        name: count for name, count in sorted(result.request_record_counts.items()) if count
    }
    st.dataframe(
        pd.DataFrame({"Record type": list(counts), "Records": list(counts.values())}),
        width="stretch",
        hide_index=True,
    )

    if result.life_events:
        st.markdown(f"##### Life events &nbsp; `{TRUTH_LABEL}`")
        st.dataframe(
            pd.DataFrame.from_records(
                [
                    {
                        "Date": event.effective_date,
                        "Event": describe(event.event_type, LIFE_EVENT_LABELS),
                        "Annualized income before": money(
                            event.annualized_income_before_minor, result.currency
                        ),
                        "Annualized income after": money(
                            event.annualized_income_after_minor, result.currency
                        ),
                    }
                    for event in result.life_events
                ]
            ),
            width="stretch",
            hide_index=True,
        )

with explanation_tab:
    month_labels = [row.month for row in result.month_rows]
    chosen_month = st.selectbox(
        "Reference month",
        options=month_labels,
        index=len(month_labels) - 1,
    )
    monthly = next(
        item
        for item in result.explanation.monthly_explanations
        if item.month == chosen_month
    )
    chosen_row = next(row for row in result.month_rows if row.month == chosen_month)

    st.markdown("##### Why this answer")
    if chosen_row.routing_reason_codes:
        for code in chosen_row.routing_reason_codes:
            st.markdown(f"- {describe(code, ROUTING_REASONS)} &nbsp; `{code}`")
    else:
        st.caption("No routing reasons were recorded for this month.")

    left, right = st.columns(2)
    with left:
        st.markdown("##### Component estimates")
        st.dataframe(
            pd.DataFrame.from_records(
                [
                    {
                        "Component": describe(item.component, COMPONENT_LABELS),
                        "Target": item.target,
                        "Estimate": money(item.estimate_minor, result.currency),
                        "Weight": basis_points(item.weight_basis_points),
                    }
                    for item in monthly.component_estimates
                ]
            ),
            width="stretch",
            hide_index=True,
        )
        if chosen_row.component_disagreement_basis_points is not None:
            st.caption(
                "Component disagreement: "
                f"{basis_points(chosen_row.component_disagreement_basis_points)}"
            )
    with right:
        st.markdown("##### Confidence breakdown")
        st.dataframe(
            pd.DataFrame.from_records(
                [
                    {
                        "Factor": describe(item.name, CONFIDENCE_COMPONENTS),
                        "Score": basis_points(item.value_basis_points),
                        "Weight": basis_points(item.weight_basis_points),
                    }
                    for item in monthly.confidence_components
                ]
            ),
            width="stretch",
            hide_index=True,
        )

    st.markdown("##### Credits considered")
    included_column, excluded_column = st.columns(2)
    included_column.markdown(f"**Counted as income ({len(monthly.included_transactions)})**")
    included_column.dataframe(
        pd.DataFrame.from_records(
            [
                {
                    "Amount": money(item.amount_minor, result.currency),
                    "Counterparty": item.counterparty_cluster,
                    "Why": ", ".join(item.reason_codes),
                }
                for item in monthly.included_transactions
            ]
        ),
        width="stretch",
        hide_index=True,
    )
    excluded_column.markdown(f"**Excluded ({len(monthly.excluded_transactions)})**")
    excluded_column.dataframe(
        pd.DataFrame.from_records(
            [
                {
                    "Amount": money(item.amount_minor, result.currency),
                    "Counterparty": item.counterparty_cluster,
                    "Why": ", ".join(item.reason_codes),
                }
                for item in monthly.excluded_transactions
            ]
        ),
        width="stretch",
        hide_index=True,
    )

    if monthly.capacity is not None:
        st.markdown("##### Feature contributions to sustainable income")
        st.caption(
            f"Model `{monthly.capacity.model_version}` predicted "
            f"{money_md(monthly.capacity.predicted_minor, result.currency)}. The gate put the "
            f"probability of non-zero capacity at "
            f"{basis_points(monthly.capacity.positive_gate_basis_points)} against a threshold of "
            f"{basis_points(monthly.capacity.gate_threshold_basis_points)}."
        )
        contributions = sorted(
            monthly.capacity.contributions,
            key=lambda item: abs(item.log_contribution),
            reverse=True,
        )[:15]
        st.dataframe(
            pd.DataFrame.from_records(
                [
                    {
                        "Feature": item.feature_name,
                        "Value": "missing" if item.is_missing_feature else item.feature_value,
                        "Contribution (log)": round(item.log_contribution, 4),
                    }
                    for item in contributions
                ]
            ),
            width="stretch",
            hide_index=True,
        )

    if result.explanation.income_streams:
        st.markdown("##### Detected income streams")
        st.dataframe(
            pd.DataFrame.from_records(
                [
                    {
                        "Counterparty": stream.counterparty_cluster,
                        "Frequency": stream.frequency,
                        "Pattern": stream.pattern,
                        "First seen": stream.first_seen,
                        "Last seen": stream.last_seen,
                        "Typical amount": money(stream.median_amount_minor, result.currency),
                        "Recurrence": basis_points(stream.recurrence_score_basis_points),
                        "Credits": len(stream.transaction_ids),
                    }
                    for stream in result.explanation.income_streams
                ]
            ),
            width="stretch",
            hide_index=True,
        )

with quality_tab:
    quality = result.data_quality
    quality_columns = st.columns(4)
    quality_columns[0].metric(
        "Consent coverage",
        basis_points(quality.overall_coverage_basis_points),
        help="Share of eligible records the consent actually exposed.",
    )
    quality_columns[1].metric("Observed transactions", f"{quality.observed_transaction_count:,}")
    quality_columns[2].metric(
        "Months with an interval",
        f"{quality.months_with_interval} of {len(result.month_rows)}",
    )
    quality_columns[3].metric("Months abstained", quality.months_abstained)

    if not quality.coverage_is_declared:
        st.caption(
            "This scenario predates the coverage contract, so full coverage is assumed for every "
            "account rather than measured."
        )

    st.markdown("##### Per-account consent coverage")
    st.dataframe(
        pd.DataFrame.from_records(
            [
                {
                    "Account": row.account_id,
                    "Configured coverage": f"{row.configured_coverage_percent}%",
                    "Eligible records": row.eligible_record_count,
                    "Observed records": row.observed_record_count,
                    "Effective coverage": basis_points(row.effective_coverage_basis_points),
                }
                for row in quality.coverage_rows
            ]
        ),
        width="stretch",
        hide_index=True,
    )

    st.markdown("##### Feed artifacts")
    st.dataframe(
        pd.DataFrame(
            {
                "Measure": [
                    "Duplicate records",
                    "Reversal records",
                    "Corrected re-posts",
                    "Late arrivals",
                    "Longest arrival delay",
                ],
                "Count": [
                    quality.duplicate_count,
                    quality.reversal_count,
                    quality.repost_count,
                    quality.late_arrival_count,
                    f"{quality.max_late_arrival_days} days",
                ],
            }
        ),
        width="stretch",
        hide_index=True,
    )

    if quality.abstention_reasons:
        st.markdown("##### Why some months published no interval")
        for reason in quality.abstention_reasons:
            st.warning(
                f"**{reason}** - " + describe(reason, QUANTILE_UNAVAILABLE_REASONS), icon="🚧"
            )

with how_tab:
    st.markdown("##### The trust boundary")
    st.caption(
        "The simulator knows everything about this client. The estimator is handed one thing: the "
        "consented observation feed. The truth is projected only after the estimate exists, and "
        "only so this page can score it."
    )

    boundary = st.columns([1, 0.12, 1, 0.12, 1])
    with boundary[0]:
        with st.container(border=True):
            st.markdown("**Simulator: the hidden world**")
            st.caption(
                "Income sources, life events, balance sheets, anomalies, and the five private "
                "income targets."
            )
    boundary[1].markdown(
        "<div style='text-align:center;font-size:2rem;padding-top:1.2rem'>→</div>",
        unsafe_allow_html=True,
    )
    with boundary[2]:
        with st.container(border=True):
            st.markdown("**Consented observation feed**")
            st.caption(
                "Accounts, balances, transactions, cards, loans, investments. This, and nothing "
                "else, becomes estimator input "
                f"`{result.input_contract_version}`."
            )
    boundary[3].markdown(
        "<div style='text-align:center;font-size:2rem;padding-top:1.2rem'>→</div>",
        unsafe_allow_html=True,
    )
    with boundary[4]:
        with st.container(border=True):
            st.markdown("**Estimator**")
            st.caption(
                f"`{result.estimator_version}` answers from the request alone and publishes "
                f"output `{result.output_contract_version}` plus explanation "
                f"`{result.explanation.schema_version}`."
            )

    st.markdown(
        f"The private layer reaches this page on one path only: **after** inference, to produce "
        f"the comparison labelled `{TRUTH_LABEL}`. In `demo_app/service.py` the inference "
        "function takes the request and nothing else, and a test asserts no private field name "
        "appears anywhere in that request."
    )

    st.markdown("##### Versions in this run")
    st.dataframe(
        pd.DataFrame(
            {
                "Component": [
                    "Scenario contract",
                    "Estimator",
                    "Feature set",
                    "Estimator input contract",
                    "Estimator output contract",
                    "Explanation contract",
                    *[f"Model {index + 1}" for index in range(len(result.model_versions))],
                ],
                "Version": [
                    result.scenario_schema_version,
                    result.estimator_version,
                    result.feature_version,
                    result.input_contract_version,
                    result.output_contract_version,
                    result.explanation.schema_version,
                    *result.model_versions,
                ],
            }
        ),
        width="stretch",
        hide_index=True,
    )

    st.markdown("##### What this proves, and what it does not")
    proves, does_not = st.columns(2)
    proves.success(
        "**What this proves**\n\n"
        "- The simulator and the estimator integrate end to end, in one process.\n"
        "- Every estimate carries its evidence: which credits counted, which did not, and why.\n"
        "- The same profile, seed, and history length reproduce identical numbers.\n"
        "- The estimator abstains from publishing an interval outside its calibrated support "
        "instead of guessing.\n"
        "- Realized income is recovered accurately even from a partial consent feed.",
        icon="✅",
    )
    does_not.info(
        "**What this does not prove**\n\n"
        "- Nothing here touches real Open Finance data, a provider, or a consent flow.\n"
        "- Accuracy is measured against the simulator's own truth, so it inherits every "
        "assumption the simulator makes.\n"
        "- One client per run is not a population metric. Published evaluation numbers come from "
        "held-out populations, not from this page.\n"
        "- Sustainable income on volatile and noisy profiles is weak, and its interval is too "
        "narrow. Both are visible above rather than hidden.\n"
        "- There is no authentication, storage, deployment, or operational hardening.",
        icon="ℹ️",
    )

# ---------------------------------------------------------------------------------------------
# 5. Export
# ---------------------------------------------------------------------------------------------

st.subheader("5. Export")
st.download_button(
    "Download evidence JSON",
    data=evidence_json(result),
    file_name=evidence_filename(result),
    mime="application/json",
    help=(
        "Profile and seed, the full estimate and explanation, artifact versions, data quality, "
        "and the private-truth comparison."
    ),
)
st.caption(TRUTH_DISCLAIMER)
